// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAll_eCBAtPjOFDbhZquZIHebNi-kVwNrI',
    appId: '1:596355080817:web:3ae7c3fb5facfb655971d0',
    messagingSenderId: '596355080817',
    projectId: 'primoxdm',
    authDomain: 'primoxdm.firebaseapp.com',
    storageBucket: 'primoxdm.appspot.com',
    measurementId: 'G-7LLDWBPERK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6AEvK8DhuWBKMQvTxEyrz0jRhJnbmw4U',
    appId: '1:596355080817:android:b4bdf993936654cd5971d0',
    messagingSenderId: '596355080817',
    projectId: 'primoxdm',
    storageBucket: 'primoxdm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaM5ZFLLRM0f22B6eCKNrqRxQ8rKeNPes',
    appId: '1:596355080817:ios:b8c999794b95b11e5971d0',
    messagingSenderId: '596355080817',
    projectId: 'primoxdm',
    storageBucket: 'primoxdm.appspot.com',
    iosBundleId: 'com.example.getgeo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaM5ZFLLRM0f22B6eCKNrqRxQ8rKeNPes',
    appId: '1:596355080817:ios:5862f34c26abf5145971d0',
    messagingSenderId: '596355080817',
    projectId: 'primoxdm',
    storageBucket: 'primoxdm.appspot.com',
    iosBundleId: 'com.example.getgeo.RunnerTests',
  );
}
